### ISSUE TITLE
The specified module could not be found.

### ISSUE THREAD

**Issue by hyousef-rusty** [fusion-engineering/inline-python#16] opened 2020-03-20 16:41 UTC
Trying to run your example at `Win 10`:
```rust
#![feature(proc_macro_hygiene)]

use inline_python::python;

fn main() {
	let data = vec![(4, 3), (2, 8), (3, 1), (4, 0)];
	python! {
		import matplotlib.pyplot as plt
		plt.plot('data)
		plt.show()
	}
}
```

Got the below error:
```bash
C:\Users\hasan.yousef\Google Drive\Rust\csv>cargo run
   Compiling inline-python v0.4.0
error: The specified module could not be found. (os error 126)
  --> C:\Users\hasan.yousef\.cargo\registry\src\github.com-1ecc6299db9ec823\inline-python-0.4.0\src\lib.rs:94:9
   |
94 | pub use inline_python_macros::python;
   |         ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `inline-python`.

To learn more, run the command again with --verbose.
```

**Comment by m-ou-se** [comment] 2020-03-20 17:18
Thanks for reporting!

We don't have Windows here, so I can't really reproduce it, unfortunately. (You might even bethe first one using `inline-python` on Windows.)

That error ("The specified module could not be found. (os error 126)") probably indicates it can't find the Python DLL, to compile the Python code with.

Can you check if [this PyO3 example](https://github.com/PyO3/pyo3#using-python-from-rust) works?

**Comment by hyousef-rusty** [comment] 2020-03-20 21:09
I got this error"
```
exit code: 0xc0000135, STATUS_DLL_NOT_FOUND
```

**Comment by de-vri-es** [comment] 2020-03-21 00:06
Could you be more specific? Could you give the full command that you ran and the full output it produced? Without it we're just guessing what may have happened.

**Comment by hyousef-rusty** [comment] 2020-03-21 11:38
@de-vri-es  nothing special, here is everything:

![image](https://user-images.githubusercontent.com/60115476/77225614-9d2ac300-6b81-11ea-8284-c6b2b60179f0.png)

**Comment by hyousef-rusty** [comment] 2020-03-21 13:50
Just tried in my personal laptop (Win 10 Home) instead of the work laptop (Win 10 Pro) but this time got different error:

> = note: python38.lib(python38.dll) : fatal error LNK1112: module machine type 'x64' coline_python_macros-1901d697edcd69db.dll.lib"nflicts with target machine type 'x86' 

Knowing that I use Win x64 and Python 3.8 for x64
![image](https://user-images.githubusercontent.com/60115476/77227777-bdfc1400-6b93-11ea-85ba-cb4202d0c0b4.png)


I was testing very simple code as below:

![image](https://user-images.githubusercontent.com/60115476/77227832-074c6380-6b94-11ea-9b16-1e4030dd05f0.png)

**Comment by de-vri-es** [comment] 2020-03-22 15:55
Thanks for letting us know that the issue is solved.

For future reference: it helps us if you post that fact in a new comment rather than an edit. That way, we get notified and we can close the issue.

Glad the problem is fixed for you :)

**Closed by de-vri-es** 2020-03-22 15:55 UTC
